
[terminal.shell]
program = "/bin/bash"
args = [
  "-l",
  "-c",
  "zellij delete-all-sessions && zellij attach || zellij --session 影",
]

[window]
opacity = 0.95
padding = { x = 10, y = 10 }
dynamic_padding = true

[font]
normal = { family = "Iosevka Nerd Font" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
size = 14.0
offset.y = 2

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 400
blink_timeout = 0

[terminal]
osc52 = "CopyPaste"

[scrolling]
history = 50000

[general]
import = ["~/.config/alacritty/plugins/papercolor_dark.toml"]
