import = ["~/.config/alacritty/plugins/dracula.toml"]

[shell]
program = "/bin/bash"
args = [
  "-l",
  "-c",
  "zellij delete-all-sessions && zellij attach || zellij --session 影",
]

[window]
opacity = 1
padding = { x = 20, y = 20 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono NF" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
size = 14.0
offset.y = 2

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 100
blink_timeout = 0

[terminal]
osc52 = "CopyPaste"

[scrolling]
history = 50000
